# Generated by Django 4.2.16 on 2024-12-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('details', models.TextField(verbose_name='商品详情')),
                ('image', models.ImageField(upload_to='goods/', verbose_name='商品图片')),
                ('price', models.FloatField(verbose_name='价格')),
                ('remain', models.IntegerField(verbose_name='库存量')),
                ('status', models.BooleanField(default=True, verbose_name='是否在架')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品表',
                'db_table': 'goods',
            },
        ),
    ]
