# Generated by Django 4.2.16 on 2024-12-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
