# Generated by Django 4.2.16 on 2024-12-12 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_delete_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_id', models.CharField(max_length=20, unique=True, verbose_name='订单号')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (3, '已取消'), (2, '已支付')], verbose_name='订单状态')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('payed_at', models.DateTimeField(auto_now=True, verbose_name='支付时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '订单表',
                'db_table': 'order',
            },
        ),
    ]
